# NumPy Crash Course

Welcome to this crash course on **NumPy**, a fundamental package for scientific computing in Python. By the end of this course, you'll understand the basics of NumPy and be able to use it for numerical computations and array manipulations.

## Topics Covered

1.  Introduction to NumPy

2.  NumPy Arrays

3.  Array Creation

4.  Basic Array Operations

5.  Indexing and Slicing

6.  Reshaping and Resizing

7.  Universal Functions (ufuncs)

8.  Array Mathematics

9.  Statistical Functions

10. Broadcasting

11. Working with Random Numbers


## 1. Introduction to NumPy

NumPy (Numerical Python) is a Python library used for working with arrays. It provides high-performance multidimensional array objects and tools for working with these arrays.

To use NumPy, you first need to import it:

```python

import numpy as np

```

NumPy is commonly imported with the alias `np`.


## 2. NumPy Arrays

The core of NumPy is the **ndarray**, where **nd** stands for n-dimensional. It's a collection of items of the same type.

**Example**:


In [13]:
import numpy as np

# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr)

1D Array:
[1 2 3 4 5]


You can check the type of the array and its data type:


In [14]:
print("Type of arr:", type(arr))
print("Data type of elements:", arr.dtype)

Type of arr: <class 'numpy.ndarray'>
Data type of elements: int64


## 3. Array Creation

There are several ways to create arrays in NumPy.

### Using `array()` Function:


In [15]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(arr_2d)

2D Array:
[[1 2 3]
 [4 5 6]]


### Using Built-in Functions:


In [16]:
# Create an array of zeros
zeros = np.zeros((2, 3))
print("Array of zeros:")
print(zeros)

# Create an array of ones
ones = np.ones((3, 2))
print("\nArray of ones:")
print(ones)

# Create an array with a range of values
range_arr = np.arange(0, 10, 2)
print("\nArray with range:")
print(range_arr)

# Create an array with linearly spaced values
linspace_arr = np.linspace(0, 1, 5)
print("\nLinearly spaced array:")
print(linspace_arr)

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Array of ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

Array with range:
[0 2 4 6 8]

Linearly spaced array:
[0.   0.25 0.5  0.75 1.  ]


## 4. Basic Array Operations

You can perform arithmetic operations on arrays.


In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
print("a + b =", a + b)

# Subtraction
print("a - b =", a - b)

# Multiplication
print("a * b =", a * b)

# Division
print("a / b =", a / b)

# Scalar operations
print("a * 2 =", a * 2)

a + b = [5 7 9]
a - b = [-3 -3 -3]
a * b = [ 4 10 18]
a / b = [0.25 0.4  0.5 ]
a * 2 = [2 4 6]


## 5. Indexing and Slicing

Access elements and subsets of arrays.


In [18]:
arr = np.array([10, 20, 30, 40, 50])

# Accessing an element
print("First element:", arr[0])

# Slicing
print("Elements from index 1 to 3:", arr[1:4])

# For 2D arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\nElement at row 1, column 2:", arr_2d[1, 2])

print("First row:", arr_2d[0, :])
print("Second column:", arr_2d[:, 1])

First element: 10
Elements from index 1 to 3: [20 30 40]

Element at row 1, column 2: 6
First row: [1 2 3]
Second column: [2 5]


## 6. Reshaping and Resizing

Change the shape of arrays.


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape to 2 rows and 3 columns
reshaped_arr = arr.reshape(2, 3)
print("Reshaped array (2x3):")
print(reshaped_arr)

# Flatten the array back to 1D
flattened_arr = reshaped_arr.flatten()
print("\nFlattened array:")
print(flattened_arr)

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]

Flattened array:
[1 2 3 4 5 6]


## 7. Universal Functions (ufuncs)

Functions that operate element-wise on arrays.


In [20]:
arr = np.array([1, 4, 9, 16])

# Square root
print("Square roots:", np.sqrt(arr))

# Exponential
print("Exponentials:", np.exp(arr))

# Sine function
angles = np.array([0, np.pi / 2, np.pi])
print("Sine of angles:", np.sin(angles))

Square roots: [1. 2. 3. 4.]
Exponentials: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Sine of angles: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


## 8. Array Mathematics

Matrix multiplication and dot product.


In [21]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

product = np.dot(A, B)
print("Matrix product of A and B:")
print(product)

Matrix product of A and B:
[[19 22]
 [43 50]]


## 9. Statistical Functions

Calculate statistical values on arrays.


In [22]:
data = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Standard deviation:", np.std(data))
print("Maximum:", np.max(data))
print("Minimum:", np.min(data))

Sum: 15
Mean: 3.0
Standard deviation: 1.4142135623730951
Maximum: 5
Minimum: 1


## 10. Broadcasting

Perform operations on arrays of different shapes.


In [23]:
arr = np.array([1, 2, 3])
scalar = 2

# Broadcasting scalar multiplication
print("arr * scalar:", arr * scalar)

# Broadcasting with different shapes
matrix = np.array([[1], [2], [3]])
print("\nArray:")
print(arr)
print("Matrix:")
print(matrix)
print("Result of broadcasting addition:")
print(arr + matrix)

arr * scalar: [2 4 6]

Array:
[1 2 3]
Matrix:
[[1]
 [2]
 [3]]
Result of broadcasting addition:
[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 11. Working with Random Numbers

Generate random numbers and arrays.


In [24]:
# Random floats between 0 and 1
rand_arr = np.random.rand(3)
print("Random floats:", rand_arr)

# Random integers
rand_ints = np.random.randint(0, 10, size=(3, 3))
print("\nRandom integers:")
print(rand_ints)

# Set seed for reproducibility
np.random.seed(0)
print("\nRandom numbers with seed 0:", np.random.rand(3))

Random floats: [0.54488318 0.4236548  0.64589411]

Random integers:
[[4 7 6]
 [8 8 1]
 [6 7 7]]

Random numbers with seed 0: [0.5488135  0.71518937 0.60276338]


## Conclusion

This NumPy crash course covered:

- Introduction to NumPy and ndarray

- Array creation methods

- Basic array operations

- Indexing and slicing arrays

- Reshaping and resizing arrays

- Universal functions (ufuncs)

- Array mathematics

- Statistical functions

- Broadcasting

- Working with random numbers

NumPy is a powerful library for numerical computing. Keep practicing to become proficient!
